name: Build
on: [push, pull_request]

jobs:
  bugswarm_dev:
    name: Test in private repo
    if: github.repository == 'BugSwarm/bugswarm-dev'
    runs-on: self-hosted
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - bugswarm/images:ubuntu-18.04
          - bugswarm/images:ubuntu-20.04
    env:
      IN_CONTAINER: true

    steps:
      - uses: actions/checkout@v2
      - name: Add Credentials
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
          travis_com_token: ${{ secrets.TRAVIS_COM_TOKEN }}
          bugswarm_api_token: ${{ secrets.BUGSWARM_API_TOKEN }}
        run: |
          cp bugswarm/common/credentials.sample.py bugswarm/common/credentials.py
          sed -i "s~GITHUB_TOKENS = \[\]~GITHUB_TOKENS = \['${gh_token}'\]~g" bugswarm/common/credentials.py
          sed -i "s~TRAVIS_TOKENS = \[\]~TRAVIS_TOKENS = \['${travis_com_token}'\]~g" bugswarm/common/credentials.py
          sed -i "s~COMMON_HOSTNAME = ''~COMMON_HOSTNAME = 'www.api.bugswarm.org'~g" bugswarm/common/credentials.py
          sed -i "s~DATABASE_PIPELINE_TOKEN = ''~DATABASE_PIPELINE_TOKEN = '${bugswarm_api_token}'~g" bugswarm/common/credentials.py
          sed -i "s~''~'#'~g" bugswarm/common/credentials.py
      - name: Installing Python 3.8
        if: matrix.container == 'bugswarm/images:ubuntu-18.04'
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y python3.8
      - name: Installing Dependencies
        run: |
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
          python3.8 -m pip install --upgrade pip==21.3.1
          pip3 install .
      - name: Lint with flake8
        run: |
          pip3 install flake8==5.0.4 flake8-quotes==3.3.2
          flake8 . --count --statistics
      - name: Test Analyzer
        working-directory: ./tests/analyzer
        run: |
          python3.8 -m unittest discover
      - name: Test Common
        working-directory: ./tests/common
        run: |
          python3.8 -m unittest discover
      - name: Test Classifier
        working-directory: ./pair-classifier/tests
        run: |
          python3.8 -m unittest discover
      - name: Test PairFilter
        working-directory: ./pair-filter
        run: |
          python3.8 -m unittest discover
      - name: Test GHA PairFinder
        working-directory: ./github-pair-finder
        run: |
          python3.8 -m unittest discover
      - name: Test Reproducer - PairChooser
        working-directory: ./travis-reproducer/tests
        run: |
          python3.8 -m unittest discover
      - name: Test GitHub Cacher
        working-directory: ./github-cacher/tests
        run: python3.8 -m unittest discover

  bugswarm_dev_build_common:
    name: Build bugswarm/common
    if: github.event_name == 'pull_request'
    needs: bugswarm_dev
    uses: ./.github/workflows/build-artifacts.yml
    with:
      artifact-name: bugswarm-common-build
      source-path: bugswarm/common
      setup-file: setup.common.py
      watched-paths: |
        bugswarm/common/**
        setup.common.py

  bugswarm_dev_build_client:
    name: Build bugswarm/client
    if: github.event_name == 'pull_request'
    needs: bugswarm_dev_build_common
    uses: ./.github/workflows/build-artifacts.yml
    with:
      artifact-name: bugswarm-client-build
      source-path: bugswarm/client
      setup-file: setup.client.py
      watched-paths: |
        bugswarm/common/**
        bugswarm/client/**
        setup.common.py
        setup.client.py

  bugswarm:
    name: Test in public repo
    if: github.repository == 'BugSwarm/bugswarm'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Add Credentials
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
          travis_com_token: ${{ secrets.TRAVIS_COM_TOKEN }}
          bugswarm_api_token: ${{ secrets.BUGSWARM_API_TOKEN }}
        run: |
          cp bugswarm/common/credentials.sample.py bugswarm/common/credentials.py
          sed -i "s~GITHUB_TOKENS = \[\]~GITHUB_TOKENS = \['${gh_token}'\]~g" bugswarm/common/credentials.py
          sed -i "s~TRAVIS_TOKENS = \[\]~TRAVIS_TOKENS = \['${travis_com_token}'\]~g" bugswarm/common/credentials.py
          sed -i "s~COMMON_HOSTNAME = ''~COMMON_HOSTNAME = 'www.api.bugswarm.org'~g" bugswarm/common/credentials.py
          sed -i "s~DATABASE_PIPELINE_TOKEN = ''~DATABASE_PIPELINE_TOKEN = '${bugswarm_api_token}'~g" bugswarm/common/credentials.py
          sed -i "s~''~'#'~g" bugswarm/common/credentials.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Lint with flake8
        run: |
          pip install flake8==6.0.0 flake8-quotes==3.3.2
          flake8 . --count --statistics
      - name: Test Analyzer
        working-directory: ./tests/analyzer
        run: |
          python -m unittest discover
      - name: Test Common
        working-directory: ./tests/common
        run: python -m unittest discover
      - name: Test Classifier
        working-directory: ./pair-classifier/tests
        run: |
          python -m unittest discover
      - name: Test PairFilter
        working-directory: ./pair-filter
        run: |
          python -m unittest discover
      - name: Test PairFinder
        working-directory: ./github-pair-finder
        run: |
          python3.8 -m unittest discover
      - name: Test Reproducer - PairChooser
        working-directory: ./travis-reproducer/tests
        run: |
          python3 -m unittest discover
      - name: Test GitHub Cacher
        working-directory: ./github-cacher/tests
        run: python3 -m unittest discover

  bugswarm_build_common:
    name: Build bugswarm/common
    if: github.event_name == 'push' && github.ref_name == 'master'
    needs: bugswarm
    uses: ./.github/workflows/build-artifacts.yml
    with:
      artifact-name: bugswarm-common-build
      source-path: bugswarm/common
      setup-file: setup.common.py
      watched-paths: |
        bugswarm/common/**
        setup.common.py

  bugswarm_build_client:
    name: Build bugswarm/client
    if: github.event_name == 'push' && github.ref_name == 'master'
    needs: bugswarm_build_common
    uses: ./.github/workflows/build-artifacts.yml
    with:
      artifact-name: bugswarm-client-build
      source-path: bugswarm/client
      setup-file: setup.client.py
      watched-paths: |
        bugswarm/common/**
        bugswarm/client/**
        setup.common.py
        setup.client.py
