name: Build

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Add Credentials
      run: |
        sed -i "s/''/'#'/g" bugswarm/common/credentials.py
        sed -i "s/'#',/'${{ secrets.GH_TOKEN }}'/g" bugswarm/common/credentials.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --max-line-length=120 --statistics
    - name: Test Analyzer
      working-directory: ./tests/analyzer
      run: |
        python -m unittest tests.py
    - name: Test Classifier
      working-directory: ./pair-classifier/tests
      run: |
        python -m unittest tests.py