name: Build
on: [push,pull_request]

jobs:
  job_1:
    if: github.repository == 'BugSwarm/bugswarm-dev'
    runs-on: self-hosted
    container: bugswarm/images:ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Add Credentials
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
        run: |
          cp bugswarm/common/credentials.sample.py bugswarm/common/credentials.py
          sed -i "s~''~'#'~g" bugswarm/common/credentials.py
          sed -i "s~\[\]~\['${gh_token}'\]~g" bugswarm/common/credentials.py
      - name: Installing Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install .
      - name: Lint with flake8
        run: |
          pip3 install flake8
          flake8 . --count --max-line-length=120 --statistics
      - name: Test Analyzer
        working-directory: ./tests/analyzer
        run: |
          python3 -m unittest discover
      - name: Test Classifier
        working-directory: ./pair-classifier/tests
        run: |
          python3 -m unittest discover
      - name: Test PairFilter
        working-directory: ./pair-filter/tests
        run: |
          python3 -m unittest discover

  job_2:
    if: github.repository == 'BugSwarm/bugswarm-dev'
    runs-on: self-hosted
    container: bugswarm/images:ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Add Credentials
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
        run: |
          cp bugswarm/common/credentials.sample.py bugswarm/common/credentials.py
          sed -i "s~''~'#'~g" bugswarm/common/credentials.py
          sed -i "s~\[\]~\['${gh_token}'\]~g" bugswarm/common/credentials.py
      - name: Installing Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install .
      - name: Lint with flake8
        run: |
          pip3 install flake8
          flake8 . --count --max-line-length=120 --statistics
      - name: Test Analyzer
        working-directory: ./tests/analyzer
        run: |
          python3 -m unittest discover
      - name: Test Classifier
        working-directory: ./pair-classifier/tests
        run: |
          python3 -m unittest discover
      - name: Test PairFilter
        working-directory: ./pair-filter/tests
        run: |
          python3 -m unittest discover

  job_3:
    if: github.repository == 'BugSwarm/bugswarm'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Add Credentials
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
        run: |
          cp bugswarm/common/credentials.sample.py bugswarm/common/credentials.py
          sed -i "s~''~'#'~g" bugswarm/common/credentials.py
          sed -i "s~\[\]~\['${gh_token}'\]~g" bugswarm/common/credentials.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --max-line-length=120 --statistics
      - name: Test Analyzer
        working-directory: ./tests/analyzer
        run: |
          python -m unittest discover
      - name: Test Classifier
        working-directory: ./pair-classifier/tests
        run: |
          python -m unittest discover
      - name: Test PairFilter
        working-directory: ./pair-filter/tests
        run: |
          python -m unittest discover
