name: Build
on: [push,pull_request]

jobs:
  bugswarm_dev:
    name: Test in private repo
    if: github.repository == 'BugSwarm/bugswarm-dev'
    runs-on: self-hosted
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - bugswarm/images:ubuntu-18.04
          - bugswarm/images:ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Add Credentials
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
          travis_com_token: ${{ secrets.TRAVIS_COM_TOKEN }}
        run: |
          cp bugswarm/common/credentials.sample.py bugswarm/common/credentials.py
          sed -i "s~''~'#'~g" bugswarm/common/credentials.py
          sed -i "s~GITHUB_TOKENS = \[\]~GITHUB_TOKENS = \['${gh_token}'\]~g" bugswarm/common/credentials.py
          sed -i "s~TRAVIS_TOKENS = \[\]~TRAVIS_TOKENS = \['${travis_com_token}'\]~g" bugswarm/common/credentials.py
      - name: Installing Python 3.8
        if: matrix.container == 'bugswarm/images:ubuntu-18.04'
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          apt-get update
          apt-get install -y python3.8
      - name: Installing Dependencies
        run: |
          python3.8 -m pip install --upgrade pip==21.3.1
          pip3 install .
      - name: Lint with flake8
        run: |
          pip3 install flake8==3.7.9
          flake8 . --count --max-line-length=120 --statistics
      - name: Test Analyzer
        working-directory: ./tests/analyzer
        run: |
          python3.8 -m unittest discover
      - name: Test Classifier
        working-directory: ./pair-classifier/tests
        run: |
          python3.8 -m unittest discover
      - name: Test PairFilter
        working-directory: ./pair-filter/tests
        run: |
          python3.8 -m unittest discover
      - name: Test Reproducer - PairChooser
        working-directory: ./reproducer/tests
        run: |
          python3.8 -m unittest discover

  bugswarm:
    name: Test in public repo
    if: github.repository == 'BugSwarm/bugswarm'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Add Credentials
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
          travis_com_token: ${{ secrets.TRAVIS_COM_TOKEN }}
        run: |
          cp bugswarm/common/credentials.sample.py bugswarm/common/credentials.py
          sed -i "s~''~'#'~g" bugswarm/common/credentials.py
          sed -i "s~GITHUB_TOKENS = \[\]~GITHUB_TOKENS = \['${gh_token}'\]~g" bugswarm/common/credentials.py
          sed -i "s~TRAVIS_TOKENS = \[\]~TRAVIS_TOKENS = \['${travis_com_token}'\]~g" bugswarm/common/credentials.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Lint with flake8
        run: |
          pip install flake8==3.7.9
          flake8 . --count --max-line-length=120 --statistics
      - name: Test Analyzer
        working-directory: ./tests/analyzer
        run: |
          python -m unittest discover
      - name: Test Classifier
        working-directory: ./pair-classifier/tests
        run: |
          python -m unittest discover
      - name: Test PairFilter
        working-directory: ./pair-filter/tests
        run: |
          python -m unittest discover
      - name: Test Reproducer - PairChooser
        working-directory: ./reproducer/tests
        run: |
          python3 -m unittest discover
