name: Build
on: [push,pull_request]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Add Credentials
      env:
        gh_token: ${{ secrets.GH_TOKEN }}
      run: |
        sed -i "s~''~'#'~g" bugswarm/common/credentials.py
        sed -i "s~\[\]~\['${gh_token}'\]~g" bugswarm/common/credentials.py
    - name: Start Environment w/ Dependencies
      run: |
        source /home/bugswarm/actions-runner/runners-venv/bin/activate
    - name: Lint with flake8
      run: |
        flake8 . --count --max-line-length=120 --statistics
    - name: Test Analyzer
      working-directory: ./tests/analyzer
      run: |
        python3 -m unittest discover
    - name: Test Classifier
      working-directory: ./pair-classifier/tests
      run: |
        python3 -m unittest discover
    - name: Test PairFilter
      working-directory: ./pair-filter/tests
      run: |
        python3 -m unittest discover
